### ISSUE TITLE
IME doesn't hide on Tizen TV

### ISSUE THREAD

**Issue by panpawel88** [Samsung/TizenFX#1117]
Hello,

We noticed that IME doesn't hide on Tizen TV. Basically, selecting 'Done' or 'Cancel' buttons does not work.

Environment: TIZEN-ONEMAIN-MuseM-RELEASE_20191104.4 (however, similar issues may be reproducible on older Tizen versions, see: https://github.com/Samsung/react-native-tizen-dotnet/pull/27#issuecomment-546654666)
TizenFX commit id: e546a6570f53be27cae7ae3fe8b1a20433cf87a3)

Steps to reproduce:
- build, install and run TizenFX/test/ElmSharp.Test
- select 'EntryTest3'
- focus on 'Hello, Tizen' text field. IME should appear.
- select 'Done' or 'Cancel'

Result:
IME doesn't not hide

Expected result:
IME shall hide. Text shall be updated.

**Comment by WonyoungChoi** [comment]
I believe this problem was fixed. please re-open, if necessary.
