### ISSUE TITLE
Package Dependency is FULLY Broken.

### ISSUE THREAD

**Issue by myungjoo** [Samsung/TizenFX#1120]
Issue:

-  Installing TizenFX's RPM packages does NOT guarantee the behavior of TizenFX.

-  A Tizen image with TizenFX may FAIL with TCT tests unless image maintainers MANUALLY check and install all related packages. This is PROHIBITED behavior since Tizen 4.0. Which means TizenFX is not complying with Tizen.

Reason:

-   Most of package installation dependency is omitted in .spec file of TizenFX.

Suggestion:

-  Add all Tizen package dependencies (Requires: ...) of the dll files in .spec file.
    - We may create a script reading .so files (P/Invoke) from .NET sources and requests dependency declarations accordingly. (or add Requires: statements in .spec file)

Note that this is a CRITICAL problem for Tizen integration and build systems.

**Comment by m-macias** [comment]
How can we reproduce this issue? What is a profile of your system?

**Comment by myungjoo** [comment]
You need to properly declare "Requires: packagenames" in .spec file, possibly, you can make it based on an analysis of ".so" file usages.

This is a common issue of ALL TIZEN profiles with .NET/C# API packages.

As long as you manually install things and rely on manually created OS images, it may seem fine, but that's the exactly something we had been tried to avoid with Tizen development.

Except for this Tizen.FX packages, **ALL** Tizen packages are guaranteed to get all depending packages installed once you try to install the package.

How to reproduce:
---
1. Remove any package from Tizen device / emulator which has an ".so" file that a Tizen-FX module use
2. Install Tizen-FX module (rpm file)
3. The module is successfully installed with RPM
4. The module fails to run
---

The supposed (correct) behavior:
---
1. same
2. same
3. RPM denies to install Tizen-FX because the dependency is not met.
   (With zypper or mic, it will install the removed package automatically.)
---

**Comment by m-macias** [comment]
@myroot @WonyoungChoi Do you have any plans for this issue? We could take a look into it.

**Comment by myungjoo** [comment]
Maybe, we need to mandate each .net API implementation declare the list of so files required and recommended.

**Comment by WonyoungChoi** [comment]
@myungjoo If the TizenFX has package dependencies for native packages, We should manage too many branches for profiles and products. The basic concept of TizenFX is to determine at runtime whether each module is supported or not. The method may be to use Feature settings or to check the presence of native so files.

**Comment by myungjoo** [comment]
You do not need branches for profiles/products. Other Tizen packages (.spec files) have been managing such differences without branches with .spec files since 2017. Any RPM packages should describe their package dependencies fully. Otherwise, image creation (mic/tic) and pkg manager (zypper) may be broken unexpectedly.

You can describe depedencies (Provides/Requires/Suggests/Enchances/...) per each subpackage.
    - Ex. csapi-tizenfx-mobile Requires ABC-mobile / csapi-tizenfx-tv Requires DEF / .... 
If you have a (sub) package that needs to use "pkg-A" or "pkg-B", then provide a common capability "cap-X" for both "pkg-A" and "pkg-B" and do require "cap-X" with "recommends: pkg-A (A is default but B can be used instead)". These dependency problems related with products and profiles were ALL visited and resolved with Tizen 4.0 under "TIzen:Unified" project, which unfied all branches or build options for all profiles/products.
