### ISSUE TITLE
Discuss on key/value type of Dictionary on Widget and ComponentBasedApplication constructor

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#1302]
Constructor of `ComponentBasedApplicationBase` and `WidgetApplication` has parameter with `Dictionary<Type,string>`

``` c#
        /// <summary>
        /// Initializes the ComponentBasedApplicationBase class.
        /// </summary>
        /// <param name="typeInfo">The component type information.
        /// The key should be a class type of FrameComponent or SubComponent subclass.
        /// The value should be a component id which is declared in tizen-manifest.xml.
        /// </param>
        /// <since_tizen> 6 </since_tizen>
        public ComponentBasedApplication(IDictionary<Type, string> typeInfo)
```
``` c#
        /// <summary>
        /// Initializes the WidgetApplication class with the type and application ID.
        /// </summary>
        /// <param name="typeInfo">Map structure for the derived class type and widget ID.</param>
        /// <since_tizen> 3 </since_tizen>
        public WidgetApplication(IDictionary<Type, string> typeInfo)
```

As I opinion, I think id string should be a key and `Type` should be a value on a dictionary.

First, Dictionary's key role is identifier, and `ID`(component/widget) working as Identifier on tzen-minifest. 
`ID`(component/widget) should not be duplicated on dictionary. 
but currently, `ID`(component/widget) is value so, could be duplicated
``` c#
new WidgetApplication(new Dictionary<Type, string>(){
    [typeof(Widget1)] = "widget1",
    // app developer miss type "widget1" instead of "widget2" but does not report error
    [typeof(Widget2)] = "widget1"
});
```

Second, Type could *NOT* be duplicated on different `ID`(component/widget)
but it should be, because Application developer want to handle with same code (type) for various widget/components. 

``` c#
new WidgetApplication(new Dictionary<Type, string>(){
    [typeof(MultiFunctionWidget)] = "widget1",
    // app developer want to handle mutiple widget with single class but can't
    [typeof(MultiFunctionWidget)] = "widget2"
});
```

How about thinks this issue?

**Comment by pjh9216** [comment]
ID should not be duplicated.
However, types are part of the design to avoid duplication.
I don't understand what it means to have different IDs for the same type of code.
To solve duplication ID, we'll consider adding the handler which can check the duplication of IDs.

**Comment by myroot** [comment]
> to have different IDs for the same type of code.

In my case, multiple widget id could be handle with a single widgetbase class. 
Do you have any reason to disallow that duplication of types?

**Comment by pjh9216** [comment]
Why do we need multiple widget IDs in the same code?
What are the benefits of doing so?
I don't know why we need different IDs with the same type because multiple instances of the same type can already be created.
At design time, mapping the same code to multiple IDs is complex and has no benefit, so it was designed.

**Comment by myroot** [comment]
This restriction prevents more flexible app development.
in my opinion, if no issue to allow duplication of type on multiple id, it better to allow duplication of types

**Comment by myroot** [comment]
A scenario of single type for multiple Ids
``` xml
<frame-component id="org.tizen.singlemode-scenario" main="true" icon-display="true" taskmanage="true" launch_mode="single">
  <label>single mode component</label>
  <icon>single.png</icon>
</frame-component>
<frame-component id="org.tizen.groupmode-scenario" main="true" icon-display="true" taskmanage="true" launch_mode="group">
  <label>group mode component</label>
  <icon>group.png</icon>
</frame-component>
```

**Comment by pjh9216** [comment]
Yes, it's flexible.
However, providing too much freedom for app developers has the disadvantage of making us unpredictable.
If you use your own id fixed within your code, you may have a potential problem.

**Comment by myroot** [comment]
Ok, I understand, it is intended design and does not want to fix, but I still don't know what is potential problem.
