### ISSUE TITLE
[ElmSharp.RoundRectangle] Rounded boundries for EvasObject

### ISSUE THREAD

**Issue by karolk98** [Samsung/TizenFX#1312]
I am trying to create Tizen renderer for Xamarin.Forms.PancakeView, which is essentially a layout extension with rounded corners, gradient background and shadow properties. I've tried using RoundRectangle to set boundaries of my View. I've managed to substitute background of my control by RoundRectangle object, however I'm having trouble limiting the boundaries of controls nested inside my PancakeView.
i.e.
`<PancakeView HorizontalOptions="FillAndExpand" HeightRequest="150" CornerRadius="20">`
`<Grid>`
`<Image Source="pancakes2.jpg" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Aspect="AspectFill" />`
                `</Grid>`
            `</PancakeView>`

I've tried calling `NativeView.SetClip(_round_rectangle_with_boundaries);`. But it seems like clipping any EvasObject by a RoundRectangle causes it to disappear. I assume this functionality (clipping any EvasObject by RoundRectangle object) is yet to be added. 

Hence my question: Is there any other way to limit EvasObject boundaries to round its corners?

I've tried setting RoundRectangle as parent to my Control, but its not possible as RoundRectangle is not a Widget.

Does Tizen offer other interface to achieve rounded corners or multicoloured bitmap background in Xamarin?
I.e. I know that Androids' VisualElementRenderer uses Drawables for this purpose.

**Comment by myroot** [comment]
![image](https://user-images.githubusercontent.com/1029155/72491615-f3b41200-385d-11ea-8e24-bf7ac33cc6da.png)
You can use SkiaSharp to draw RoundRect and fill with gradient
``` c#
            canvas.Clear();
            SKPaint paint = new SKPaint
            {
                Style = SKPaintStyle.Fill,
            };

            var rect = e.Info.Rect;

            paint.ImageFilter = SKImageFilter.CreateDropShadow(1, 1, 2, 2, Color.Black.ToSKColor(), SKDropShadowImageFilterShadowMode.DrawShadowAndForeground);
            paint.Shader = SKShader.CreateLinearGradient(
                                        new SKPoint(rect.MidX, rect.Top),
                                        new SKPoint(rect.MidX, rect.Bottom),
                                        new SKColor[] { SKColors.Red, SKColors.Blue },
                                        new float[] { 0, 1 },
                                        SKShaderTileMode.Repeat);

            canvas.DrawRoundRect(rect, 30, 30, paint);
```
here is reference
https://docs.microsoft.com/ko-kr/xamarin/xamarin-forms/user-interface/graphics/skiasharp/

**Comment by karolk98** [comment]
Thank you, seems like SkiaSharp is the optimal way for now. However, I'm still not sure how will I limit the view of nested controls. I'll probably try drawing the outside of the control with Window Color(it's still not ideal but at least I got someting) using SkiaSharp aswell. If you know a better way please keep me posted.

P.S. Thanks for the code sample, It really helped me out a lot.
