### ISSUE TITLE
Run on device fails: "Netcoredbg is supported from Tizen 5.0"

### ISSUE THREAD

**Issue by bruno-garcia** [Samsung/TizenFX#1405]
I'm trying to run a sample from [Tizen Samples](https://github.com/Samsung/Tizen-CSharp-Samples) but I'm getting the error:

`Netcoredbg is supported from Tizen 5.0`

The TV is indeed Tizen 4.0 but is says there are no updates:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1633368/74454450-e9336b00-4e51-11ea-96de-ecda52eb4447.png">

I'm aware Tizen.NET was introduced to .NET Core 2.0 and Tizen 4.0. 

[Tizen.NET.Sdk](https://www.nuget.org/packages/Tizen.NET.Sdk/) has no dependencies so I assume it doesn't care what the target Tizen OS version is. Is that a correct assumption?

[Tizen.NET version 6](https://www.nuget.org/packages/Tizen.NET/) multi targets, including a build for Tizen 4:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1633368/74454248-9bb6fe00-4e51-11ea-899b-4b50ce22ab20.png">

That makes me believe having the package references as follows should work just fine:

```
  <ItemGroup>
    <PackageReference Include="Tizen.NET" Version="6.0.0.14995" />
    <PackageReference Include="Tizen.NET.Sdk" Version="1.0.9" />
  </ItemGroup>
```

I'm trying to run [this sample](https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/TV/FlexContainerSample), I can't see any setting for Tizen 4 vs Tizen 5. The TFM used is `netcoreapp2.0`.

Is there a way for me to get this to run on this Tizen 4 device? Some project setting or something?

Note: I went through the [known issues](https://samsung.github.io/Tizen.NET/issues/tv/2018SmartTV/#) but this doesn't seem to be related to any of them:

> Issues on the Smart TV device
    * Any applications loading third-party libraries (including .so files) are not allowed, because of Samsung Smart TV’s security policy.
    * Interoperability is not allowed on Samsung Smart TV, because of security risks.
    * Test automation (such as with Appium) for the application is not available, because sdb shell is not available.
    * The application installed through your SDK will not be shown and is deleted when the TV device is rebooted.

**Comment by WonyoungChoi** [comment]
@bruno-garcia The netcorredbg is available from tizen 5.0 platform regardless of TFM (API Level).  As far as I know, the Tizen 4.0 platform is using lldb based debugger. We will update our known issues page in more detail.

**Comment by bruno-garcia** [comment]
Thanks for the clarification @WonyoungChoi .
How can I get `lldb` to work then? Months ago i was able to debug a Tizen 4 watch but I removed all the tools at that time and installed everything new again. Now I can't find Tizen 4 TV SDK on the package manager:
The TV icon not showing up:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1633368/75829135-68460000-5d7b-11ea-8205-f06d5261acfc.png">

Found online to use the Extensions SDK but I only see 5.5:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/1633368/75829174-7e53c080-5d7b-11ea-982b-d22005431c25.png">

Watch and Phone have have Tizen 2.3 all the way to 5.5 available, but not TV.

**Comment by WonyoungChoi** [comment]
@bruno-garcia Yes, the package manager of Tizen Studio only provides the latest version of TV Extensions now 😢 But you can download a specific old version and add to the package manager. 
Please see: 
- https://developer.samsung.com/SmartTV/develop/getting-started/setting-up-sdk/installing-tv-sdk.html#installing-required-extensions
- https://developer.samsung.com/SmartTV/develop/tools/tv-extension/archive.html
