### ISSUE TITLE
In-app purchase missing

### ISSUE THREAD

**Issue by Csaba8472** [Samsung/TizenFX#1440]
hello

do you plan to add [IAP integration](https://developer.samsung.com/galaxy-watch-iap/overview.html)? If not is there a way to call the native IAP library from the xamarin app?

Thank you!

**Comment by Juwols** [comment]
Hi
Yes We have. It's in the analysis phase, so detailed schedule is not available yet.
We'll keep you posted with any updates.
Thanks.

**Comment by Csaba8472** [comment]
thank you, is there a branch or a PR about?

**Comment by WonyoungChoi** [comment]
@Csaba8472 Not yet. IAP module is in our incubator now. I hope it will be released as soon as possible.
