### ISSUE TITLE
Wifi method signature

### ISSUE THREAD

**Issue by Kamil-Stepaniuk** [Samsung/TizenFX#1514]
There is unnecessary casting in class Tizen.Network.WiFi.WiFiAP in methods: ConnectAsync() and  ConnectWpsAsync(...). Both methods actually returns Task<bool> but signature is Task. Return info is important here.

**Comment by myroot** [comment]
It is intented, These apis not return meaningful value. if connection was failed, exception was raised instead of returning value.
Actually, We need to use TaskCompletionSource, but it is not provide for `Task`
