### ISSUE TITLE
[Badge] Can't get all the badge information.

### ISSUE THREAD

**Issue by p-czaja** [Samsung/TizenFX#1584]
**1. Issue description:**
When trying to get all the badge information using [getBagdes()](https://developer.tizen.org/dev-guide/csapi/api/Tizen.Applications.BadgeControl.html#Tizen_Applications_BadgeControl_GetBadges) function InvalidOperationException exception is thrown.
**2. Test app:** [BadgeTest](https://github.sec.samsung.net/p-czaja/BadgeTest).
**3. Tested on:**
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

**Comment by p-czaja** [comment]
Is there any progress regarding this issue?

**Comment by p-czaja** [comment]
Dear @mk5004lee,
I put a [log](https://github.com/Samsung/TizenFX/files/4648628/log.txt) of the test application execution.

**Comment by mk5004lee** [comment]
There was no badge, so received not_exist error.
I/BADGE   ( 2724): badge_internal.c: _badge_get_list(419) > [SECURE_LOG] [_badge_get_list : 419] badge db has no data
E/DATA_PROVIDER_MASTER( 2724): badge_service.c: badge_get_badge_list(283) > [SECURE_LOG] Failed to get list [-17956860]
E/DATA_PROVIDER_MASTER( 2724): badge_service.c: _badge_dbus_method_call_handler(105) > [SECURE_LOG] Badge service fail, method_name[get_list] err[-17956860]
E/BADGE   (25625): badge_ipc.c: _send_sync_badge(380) > [SECURE_LOG] [_send_sync_badge : 380] _send_sync_badge cmd = get_list, error GDBus.Error:org.freedesktop.Badge.Error.NOT_EXIST: badge service error
E/Tizen.Applications.Badge(25625): BadgeErrorFactory.cs: GetException(47) > GetBadges : 246
E/Tizen.Applications.Badge(25625): BadgeErrorFactory.cs: GetException(61) > Failed to get badges
D/BadgeTest(25625): Home: TestBadge(25) > DoesnotExist error occurred.
D/BadgeTest(25625): Home: TestBadge(27) > No exception

**Comment by p-czaja** [comment]
You have rihgt - it is working if number of badges is greater than 0.
However don't you think that in case there is no any badge, GetBadges() should return empty list of badges instead of throwing InvalidOperationException?

**Comment by mk5004lee** [comment]
We decided not to change behavior the function.

**Comment by WonyoungChoi** [comment]
@mk5004lee Could you explain why did you decide not to change it?
Currently, user doesn't know whether the badge is present or not. Furthermore, there is no explanation that InvalidOperationException occurs when there is no badge in API description.
