### ISSUE TITLE
[ElmSharp][Calendar] Calendar widget not supported on TV profile.

### ISSUE THREAD

**Issue by Machinero** [Samsung/TizenFX#1606]
1. Issue description:
Since update of tizen sdk to version 1.0.9 at the [CalendarComponent](https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/TV/CalendarComponent) sample application, the widget has stooped working on the tv profile. The message "Not supported" appears in the calendar area. In the other hand the similar application on [Mobile](https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Mobile/CalendarComponent) profile works well.
2. Tested on: TV emulator 5.5.
3. Is there any substitute component if the current one is no longer supported?

**Comment by patuwwy** [comment]
Is this a mistake or did you really remove it from tv profile?

**Comment by WonyoungChoi** [comment]
@Machinero  It is only supported in mobile profile. The TV sample app has been removed.
