### ISSUE TITLE
[NFC] Native Callback GC issue

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#1670]
https://github.com/Samsung/TizenFX/blob/98dcbeeefd4172dbe9fab93fafe101200ce6255e/src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs#L192

https://github.com/Samsung/TizenFX/blob/98dcbeeefd4172dbe9fab93fafe101200ce6255e/src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs#L225

https://github.com/Samsung/TizenFX/blob/98dcbeeefd4172dbe9fab93fafe101200ce6255e/src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs#L260

https://github.com/Samsung/TizenFX/blob/98dcbeeefd4172dbe9fab93fafe101200ce6255e/src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs#L295

It could be released by GC before complete async operation

**Comment by WonyoungChoi** [comment]
Similar issue: #1650
