### ISSUE TITLE
[Bluetooth] Native Callback GC issue

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#1671]
https://github.com/Samsung/TizenFX/blob/98dcbeeefd4172dbe9fab93fafe101200ce6255e/src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs#L119

https://github.com/Samsung/TizenFX/blob/98dcbeeefd4172dbe9fab93fafe101200ce6255e/src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs#L217

https://github.com/Samsung/TizenFX/blob/98dcbeeefd4172dbe9fab93fafe101200ce6255e/src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs#L238

Native Callback could be released by GC before completed async operation

**Comment by WonyoungChoi** [comment]
Similar issue: #1650
