### ISSUE TITLE
[Push] Native Callback GC issue 

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#1673]
Native Callback could be released by GC before completed async operation

https://github.com/Samsung/TizenFX/blob/ee50efa586a41fe0003ef71eda192aefd9c755e2/src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushImpl.cs#L148
https://github.com/Samsung/TizenFX/blob/ee50efa586a41fe0003ef71eda192aefd9c755e2/src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushImpl.cs#L196
If PushServerReigster was called twice before complete first request, native callback was overrited and first native callback could be released by GC

**Comment by WonyoungChoi** [comment]
@randeepsingh01 The similar issue #1650 will help to solve.

**Comment by myroot** [comment]
PushServerRegister has a guard for check native callback 
https://github.com/Samsung/TizenFX/blob/ee50efa586a41fe0003ef71eda192aefd9c755e2/src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushImpl.cs#L141
So, PushServerRegister has not issue for GC

**Comment by randeepsingh01** [comment]
@myroot if it doesn't have any issue then can we close it ?
