### ISSUE TITLE
[ElmSharp] Image.LoadAsync returns fail when it is called with stream source.

### ISSUE THREAD

**Issue by shyunMin** [Samsung/TizenFX#1725]
### Description
`Image.LoadAsync(Stream)` returns fail after Image has been loaded with other source such as file or uri. This problem occurs from 5.5 wearable.

| Loading the first image(file) | Loading the second image(stream) |
|-|-|
|<img src="https://user-images.githubusercontent.com/20968023/85093951-88190b00-b228-11ea-8baa-7bd02314f356.png" width="200" /> |<img src="https://user-images.githubusercontent.com/20968023/85093957-8b13fb80-b228-11ea-89ba-0512ad4ba1ac.png" width="200" />|

You can see "Loading Falied." message under the picture.
I've figured out that `"load,error"` callback is invoked internally during the second image loading(using stream source). However It was not occurred on 4.0 wearable

### Steps to Reproduce
1. Run ElmShar.Test app (https://github.com/Samsung/TizenFX/tree/master/test/ElmSharp.Test)
2. Click "ImageTest1"
3. Click any button except "StrmA" bubton
4. After checking image has been loaded, click "StrmA" button.

**Comment by shyunMin** [comment]
There is the same issue on F-hub (Tizen 6.x binary)

**Comment by arosis78** [comment]
Native EFL is fixed (https://review.tizen.org/gerrit/#/c/platform/upstream/efl/+/238746/)
