### ISSUE TITLE
NUI Wrong Property Changed notify

### ISSUE THREAD

**Issue by idkiller** [Samsung/TizenFX#1740]
## Duplicated PropertyChanged event

https://github.com/Samsung/TizenFX/blob/4e623c9551428cf98de8a930267304b9ea8dbff4/src/Tizen.NUI/src/public/BaseHandle.cs#L127

https://github.com/Samsung/TizenFX/blob/4e623c9551428cf98de8a930267304b9ea8dbff4/src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs#L51

The two events have the same purpose, but are used in different places, and the associated methods are different. As a result, the bottom problem or various other problems occur, and people who use the API become confused.

## Wrong changed notify

https://github.com/Samsung/TizenFX/blob/4e623c9551428cf98de8a930267304b9ea8dbff4/src/Tizen.NUI/src/public/BaseComponents/View.cs#L264-L285

if `viewStyle is not null, value set the BackgroundColor of viewStyle but do not fire`PropertyChanged` event that originally triggered in `SetValue`. 
it makes bindings in xaml or property changed event not working properly.

This happens also in many other places (like following properties)

* BackgroundImage
* BackgroundImageBorder
* Opacity
* Color

and `SetProperty` method also don't fire `PropertyChanged` event. (In following properties)

* TooltipText
* PositionUsesAnchorPoint
* AnchorPoint
* PaddingEX

some property like `Layout` don't fire event in specific case.

https://github.com/Samsung/TizenFX/blob/4e623c9551428cf98de8a930267304b9ea8dbff4/src/Tizen.NUI/src/public/BaseComponents/View.cs#L2156-L2161

Many properties not covered here do not fire PropertyChanged events at all, or only in certain situations.

In my opinion, `PropertyChanged`, `PropertySet` must be unified, and what happens when a Property is set must be performed in the `PropertyChanged` event when it is a `BindableProperty`.

The code is getting too complicated because things that happen when the property is changed are inconsistent.

**Comment by elishateng** [comment]
Hello, I'm checking this issue.
