### ISSUE TITLE
[MediaPlayback] Continue playback after interruption

### ISSUE THREAD

**Issue by Csaba8472** [Samsung/TizenFX#1827]
Based on the [documentation](https://docs.tizen.org/application/dotnet/guides/multimedia/media-playback/) app can subscribe some sort of notifications. What I don't find there is, how can an app continue audio playback after e.g a samsung health announcement? There is a [deprecated api](https://docs.tizen.org/iot/api/4.0/tizen-iot-headed/group__CAPI__MEDIA__AUDIO__IO__MODULE.html#ga7bba635edcca6a4a88e8c72474952489) which could notify the app about completed interruption but I haven't found this api's replacement.

**Comment by aferin** [comment]
@Csaba8472 

> The player works based on the audio session manager policy. This means that an application can be interrupted by another application. You can change the policy directly by using the Tizen.Multimedia.AudioStreamPolicy class.

As it is written in the [document](https://docs.tizen.org/application/dotnet/guides/multimedia/media-playback/), you can use AudioStreamPolicy class.
Please refer to [this page](https://samsung.github.io/TizenFX/latest/api/Tizen.Multimedia.AudioStreamPolicy.html) for details.
