### ISSUE TITLE
[API Reference] Please change the Guides link on GNB

### ISSUE THREAD

**Issue by journey2w** [Samsung/TizenFX#1871]
I found that the Guides link is wrong on  https://samsung.github.io/TizenFX/latest/ and https://samsung.github.io/TizenFX/API6/ (I know it's a symbolic link).

We don't maintain all pages on https://developer.tizen.org/development/guides-0 anymore.

Please change the link to **https://docs.tizen.org/application/dotnet/**.

**Comment by WonyoungChoi** [comment]
@journey2w Thank you for reporting. It was fixed in https://github.com/TizenAPI/TizenFX-Docs/commit/3a715c97da2fc2fce300eca7c1618bedd2fd24af. Document site will be updated in few hours.
