### ISSUE TITLE
Machine Learning Inference is not supported on Samsung Tizen TV

### ISSUE THREAD

**Issue by luannd** [Samsung/TizenFX#1884]
Hi,

I followed the documentation of .NET development on Tizen platform: https://docs.tizen.org/application/dotnet/guides/machine-learning/overview/ 

But it turns out the Tizen.MachineLearning.Inference is not supported on Tizen TV. Do you have any solutions to solve this problem? 

![IMG_20200803_145310](https://user-images.githubusercontent.com/8140854/89234061-ebc08300-d59f-11ea-8c3c-2dd7a53df301.jpg)

**Comment by WonyoungChoi** [comment]
@luannd Could you tell me the tizen platform version of your TV device?

**Comment by luannd** [comment]
@WonyoungChoi it's T-NKMAKUC-0013.90

**Comment by WonyoungChoi** [comment]
The required feature `http://tizen.org/feature/machine_learning.inference`  seems to be disabled on all TV binaries now. 
@myungjoo Could you share the current status about MM.Inference feature on TV?

**Comment by myungjoo** [comment]
Yes, TV products has not accepted ML.Inference. They need to accept and include ML.Inference to enable this in their products. (need TV-PM as well)

**Comment by myungjoo** [comment]
@luannd As I've mentioned in an email-reply yesterday, because you are affiliated with VD and we need VD's internal request to have ML.Inference included in VD's TV OS images, you may need to request directly to VD's PM or SW-Platform architect.

**Comment by luannd** [comment]
Thanks for your reply here as well as in the email thread. Close for now.

**Comment by hmthanh** [comment]
- 

1. 

- [ ]

**Comment by myungjoo** [comment]
@luannd FYI: VD has accepted Tizen Machine Learning along with both Single and Pipeline APIs w/ nnstreamer support in 2021.4. If you use Tizen 6.5 they should be available.
