### ISSUE TITLE
Question: How do i keep my app on foreground when doing a "Instant On" on the TV?

### ISSUE THREAD

**Issue by WanftMoon** [Samsung/TizenFX#1940]
Hello, 

I got a Tizen.NET TV app (xamarin forms) that go reject for the reason that it did not came back after an "Instant On" on the TV (turn it off for 15 secs and then turn the TV ON). Is there any configuration or code that must be done for it to work? 
 
here is the QA issue.

Check Item Title
Power Sequence를 통하여 하기 항목을 확인한다.

* TV 메뉴 설정 : 시스템 > 전문가 설정 > 앱자동 실행 (켜짐)
1. 파워키 입력 후 15초 이내 전원키 입력하여 TV를 켤때 컨텐츠 이어보기나 App의 초기화면을 보여주여 주는지 확인 한다.
2. Coldboot 이후 이전에 실행된 앱이 실행하는지 확인한다.
- Clodboot 조건 : 파워키 입력 후 15초에서 1분 15초 사이 전원키 입력하여 TV를 켤때.
* TV Booting 시 TV Logo가 출력되어야 한다.
3. Instant On일때 컨텐츠 이어보기나 App의 초기화면을 보여주여 주는지 확인 한다.
- Instant On 조건 : 파워키 입력 후 1분 15초 이후 전원키 입력하여 TV를 켤때.
* 3회 재현하여 3회 연속 문제점 발생될때에만 문제점으로 등록한다.

* 1, 3번에서는 Samsung waiting screen이 표시되지 않아야 하며, 2번 항목은 App이 실행되면 안됨

※ 18년도 TV는 별도 공지가 있을때까지 검증 제외한다.
Actual Result
When Instant On(after 1 minute 15 seconds) is performed, the video is not played and the live screen is displayed.

Instant On 동작시(1분 15초 이후), 영상 실행되지 않고 방송화면이 표시됨.
Expected Result
The video should be played normally.

영상이 정상적으로 재생되어야함.
Procedure
1. Launch the app
2. Run any video
3. TV off
4. Wait 2 minute
5. Turn on the TV
6. Check the defect

att.

**Comment by WonyoungChoi** [comment]
@WanftMoon I think the Smart TV developer forum is more appropriate.  https://forum.developer.samsung.com/c/smart-tv/
