### ISSUE TITLE
[NUI] unnecessary code is found at codes for default value of BindableProperty.

### ISSUE THREAD

**Issue by idkiller** [Samsung/TizenFX#1953]
https://github.com/Samsung/TizenFX/blob/3b37f25432ed45e03ef16be710b20c850aa86931/src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs#L753-L756

This code fixes the value of BindableProperty with defaultValueCreator as default value.
Why do you need this code?

**Comment by dongsug-song** [comment]
@elishateng 
Hello,
I sorry, I missed this issue.
Could you check this? I can see your comment on the snipped code above.
Thank you.

**Comment by dasg34** [comment]
Hmm,, i think we need dali value getter callback?
`DefaultValueCreator` is being used to get dali property value.
