### ISSUE TITLE
Read total number of steps since midnight (Pedometer)

### ISSUE THREAD

**Issue by ControlAdad** [Samsung/TizenFX#2057]
Hi
Using sensor listeners we can read the number of steps user taken since starting the sensor.
But how can one read the total number of steps taken by using since midnight, regardless of using our watch face or not.

**Comment by bwikbs** [comment]
Of course you've already checked, but...
https://docs.tizen.org/application/dotnet/guides/location-sensors/device-sensors/#pedometer
Currently, there is no way to get the number from a specific point. If you want that, you have to store and process it in the app side.
