### ISSUE TITLE
[Tizen.NUI.Window.System] Unsupported on iot profile

### ISSUE THREAD

**Issue by stanluk** [Samsung/TizenFX#2067]
The TizenShell and related objects are unavailable on Tizen IoT profile, the following exception occurs:

I/DOTNET_LAUNCHER( 3809):  
I/DOTNET_LAUNCHER( 3809): System.PlatformNotSupportedException: Not Supported Feature
   at Tizen.NUI.WindowSystem.Shell.TizenShell..ctor()
   at Oobe.Common.Services.SoftKeyClientService..ctor() in /home/stanluk/Projekty/Samsung/oobe/Oobe/Oobe.Common/Services/SoftKeyClientService.cs:line 32

According to project files this seems like iot profile is not enlisted in: 
cat src/Tizen.NUI.WindowSystem/Tizen.NUI.WindowSystem.csproj | grep SupportedProfiles
    <SupportedProfiles>mobile;wearable</SupportedProfiles>

Is there are reason why this API is disabled on iot-profile?

**Comment by WonyoungChoi** [comment]
Tizen.NUI.WindowSystem.dll has been added to the building block for IoT profile.
https://git.tizen.org/cgit/tools/building-blocks/commit/?h=tizen&id=5340637cc868154bda8856294390e3bbcb2c48e4
