### ISSUE TITLE
[Multimedia] Player.DisplaySettings.Mode has failed to update in Preparing state

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#227]
Always failed to update  Player.DisplaySettings.Mode in preparing state

There is no constraint in document to update Player.DisplaySettings.Mode 

https://developer.tizen.org/dev-guide/csapi/api/Tizen.Multimedia.PlayerDisplaySettings.html#Tizen_Multimedia_PlayerDisplaySettings_Mode

**Comment by kqjy777** [comment]
most of funcions dont work on preparing state basically.
since native API sets dont have preparing state, it might not be considered on c# document.
I'll try to figure out how to document it.

**Comment by hsgwon** [comment]
Preparing state is only for PrepareAsync method. 
So, How about document that restriction in PrepareAsync method?

**Comment by kqjy777** [comment]
i've documented it.
https://github.com/Samsung/TizenFX/pull/622
