### ISSUE TITLE
Problem with calling constructor System.Xml.XmlSerializer.XmlSerializer

### ISSUE THREAD

**Issue by gitchomik** [Samsung/TizenFX#2283]
Hi,

I have got strange problem with `System.Xml.XmlSerializer.XmlSerializer`
It seem that app hang on calling constructor `new XmlSerializer(typeof(A))`

Steps:
1. I have create Visual Studio. NET -> New project ->Visual C# -> "Tizen Samsung TV 5.0" ->Blank App (Xamarin.Form)
3. I add 
`
public class A
{
}
`
2. in `Main(string[] args)` I just add line (at the begining)
`
var xmlSerializer = new XmlSerializer(typeof(A));
`
3. same problem when using
`
var factory = new XmlSerializerFactory();
`
but this time, app hangs on lilne below
`
factory.CreateSerializer(typeof(A));
`
4. Then 
- build app (debug mode)
- debug on ma TV using VS.NET
- apps starts on TV
- debuger attached on VS.NET
- in debuger step in to `new XmlSerializer(...)`
- debbuger hungs on this line
- app hungs on TV
- same probelm without debbuger (build Release, install using sdb, then just run on TV)

Testing enviroment:
- Visual Studio. NET 2017 15.9.29
- Tizen.NET (5.0.0.14562)
- Tizen.NET.TV (5.5.0.4922)
- Project Sdk="Tizen.NET.Sdk/1.0.9
- TargetFramework=tizen50
- tested on TV U58RU7172UXXH

Regards!

**Comment by HJLeee** [comment]
Hello,

Thank you for the issue reporting.
I've tried to reproduce the issue on my side but failed with this code below.
![image](https://user-images.githubusercontent.com/1029226/100397369-a8c57680-308c-11eb-8f3c-ea5c480d8695.png)

These are several things you could try:
- VS2017 is not offcially supported, please use VS2019.
- Please update Tizen Studio to the latest.
- Please check if `type A` in your code is public and non-internal class like `type B` in the below
![non_public](https://user-images.githubusercontent.com/1029226/100397411-e1fde680-308c-11eb-8069-17c7557b0207.JPG)
