### ISSUE TITLE
default values of the Visuals horizontal and vertical alignments

### ISSUE THREAD

**Issue by mgrudzinska** [Samsung/TizenFX#2311]
**Description:**
The default values of the horizontal and vertical alignments of Visuals does not seem to be `Center`, as it is set in VisualMap class definition: 
 
https://github.com/Samsung/TizenFX/blob/master/src/Tizen.NUI/src/public/VisualMaps.cs

        /// <summary>
        /// Gets or sets the origin of the visual within its control area.<br />
        /// By default, the origin is center.<br />
        /// Optional.
        /// </summary>
        /// <since_tizen> 3 </since_tizen>
        public Visual.AlignType Origin
        {
            get
            {
                return _visualOrigin ?? (Visual.AlignType.Center);
            }
            set
            {
                _visualOrigin = value;
                UpdateVisual();
            }
        }

        /// <summary>
        /// Gets or sets the anchor point of the visual.<br />
        /// By default, the anchor point is center.<br />
        /// Optional.
        /// </summary>
        /// <since_tizen> 3 </since_tizen>
        public Visual.AlignType AnchorPoint
        {
            get
            {
                return _visualAnchorPoint ?? (Visual.AlignType.Center);
            }
            set
            {
                _visualAnchorPoint = value;
                UpdateVisual();
            }
        }

**Example:**
sample code available under this link:
https://github.com/mgrudzinska/NUI_issue_samples/tree/issue_samples/NUI_tests_align

**Result:**
result from the code:
![align_sample](https://user-images.githubusercontent.com/67589014/100739258-1ba95700-33d7-11eb-80c0-67f0268f5402.png)

**Comment by mgrudzinska** [comment]
@dongsug-song  could I please get  some update in the subject?

**Comment by rabbitfor** [comment]
@mgrudzinska Sorry for the late update.
I checked the default value, it was "TopBegin" as you pointed out, so I correct the description of it.

https://github.com/Samsung/TizenFX/pull/2847

Thank you.
