### ISSUE TITLE
Why is the entire Tizen.Account.OAuth2 namespace marked as obsolete?

### ISSUE THREAD

**Issue by olavaukan** [Samsung/TizenFX#2333]
Hi,

Maybe this is a silly question, but why is the entire Tizen.Account.OAuth2 namespace marked as obsolete when there is no obvious replacement? The PR #1094 refers to an internal Samsung Jira that I cannot access so I can't follow the whole thread of why this was done. Does this mean that OAuth2 support will be removed from Tizen at some point in the future?

The documentation contains info about how to authenticate using OAuth2 (https://docs.tizen.org/application/dotnet/guides/personal/oauth/) but no mention of it being obsolete or deprecated.

**Comment by myroot** [comment]
Hi, 
OAuth2 implementation was not completed in TizenFX. and We no plan to update it, so it was obsoleted, 
But, actually OAuth2 is not need platform implementation, alternatively you can use .net standard API 
[here](https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Mobile/OAuthExample) is a example of OAuth2
and [here](https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Mobile/GoogleAPIExample) is a example of Google API

**Comment by olavaukan** [comment]
Aah, I see... That example is just using "plain" HTTP-requests, so I guess technically there is no need for an extra library. It's not really a platform-level issue, since this is all just HTTP. I suppose I could find a .NET standard-compliant library that wraps this up for me if I wanted to.

Thanks for the explanation and the quick response!
