### ISSUE TITLE
STT not available when offline

### ISSUE THREAD

**Issue by tomh4** [Samsung/TizenFX#2350]
Hello,

is STT only an online feature? I could not find any documentation saying it was required to be online, but when trying to start STT while offline I am getting Time out errors.

Is that expected to happen?
Is there no Speech To Text that happens offline on Tizen Wearable? Even if it would be just some basic keywords?

**Comment by urmain** [comment]
Hello, 
Thank you for your interest.
STT is not online feature, but current STT engine uses network to recognize user's speech. 
So, STT doesn't depend  on network, but STT engine on Tizen Wearables are using network. 
But, in public Tizen Platform, we're working on an on-device STT engine without network. 
I expect that you can use STT feature without network, soon. 

Thanks,
