### ISSUE TITLE
Check Tizen Version failed

### ISSUE THREAD

**Issue by RENO-911** [Samsung/TizenFX#2429]
Hey devs,

I'm getting the following error when trying to install my tizen watchface on an Active 2.
![image](https://user-images.githubusercontent.com/75809449/102470302-18a79b00-4054-11eb-9eb8-4b83c1dbe1a7.png)
`[0m[1;31m| ERROR   |[0m CheckTizenVersion         : step_check_tizen_version.cc:89       : Package's dotnet API level(5.5) is higher than platform dotnet API level(4)`

Installing the app worked fine when using the previous settings:
.csproj:
`  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>tizen50</TargetFramework>
    
    <TargetFrameworkIdentifier>Tizen</TargetFrameworkIdentifier> 
    <TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
....
  </PropertyGroup>`

tizen-manifest.xml:
`<manifest package="packagename" version="0.0.999" api-version="4" xmlns="http://tizen.org/ns/packages">.`

Tizen.Net package version: 6.0.0.14995

But when updating to the following settings:
.csproj:
`<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>tizen60</TargetFramework>
    
    <TargetFrameworkIdentifier>Tizen</TargetFrameworkIdentifier> 
    <TargetFrameworkVersion>v6.0</TargetFrameworkVersion>
</PropertyGroup>`

tizen-manifest.xml:
`<manifest package="packagename" version="0.0.999" api-version="5.5" xmlns="http://tizen.org/ns/packages">.`

Tizen.Net package version: 6.0.0.14995

The application can no longer be installed, see error above. I'm trying to install on a physical Active 2 device, running Tizen version: 5.5.0.1. I have no idea how to fix this and what exactly the consequences are of the changes in the .csproj / manifest.

In package manager under Main SDK, i have installed the 4.0 & 5.5 wearable packages

I'm probably doing something wrong, have had no luck with the documentation.

**Comment by WonyoungChoi** [comment]
The MR version Tizen 5.5.0.1 has a bug related with the dotnet API version. It will be fixed in next MR update.
In workaround, how about just setting the "api-version" to 4 in tizen-manifest.xml to avoid the checking API version.
