### ISSUE TITLE
NUI button style

### ISSUE THREAD

**Issue by Kamil-Stepaniuk** [Samsung/TizenFX#2456]
Setting style for button by passing parameter to constructor no longer works. There is demonstrator attached; you can simply comment and uncomment two ways of button preparation.

[ButtonStyleDemonstrator.zip](https://github.com/Samsung/TizenFX/files/5734856/ButtonStyleDemonstrator.zip)

Tested on RPI4:
Tizen6/Unified 6.5.0 (arm)
VERSION = 6.5.0
CODENAME = TSDF
BUILD_ID=tizen-unified_20201221.1_tizen-headed-3parts-armv7l-rpi

**Comment by dasg34** [comment]
Thank you for the report!
It will be fixed by https://github.com/Samsung/TizenFX/pull/2442 :)

**Comment by dasg34** [comment]
This issue has been fixed on tizen-unified_20201228.6.
