### ISSUE TITLE
Inconsistent API in GPIO edge callback

### ISSUE THREAD

**Issue by kwieclaw** [Samsung/TizenFX#2754]
Currently, the implementation uses Read() to create EventArgs in Peripheral.Gpio.OnInterrupted. Unfortunately, value can change from the moment callback was called to the moment of calling Read(). This can result in passing value High, when user registered only on falling edge. That makes this parameter basically useless and misleading.

This parameter should be either dropped or changed to provide consistent and deterministic results.

**Comment by xerrni** [comment]
#2737 - ready to be merged, and is necessary for:
#2798 which provides fix for this.

**Comment by xerrni** [comment]
#2737  - merged
#2798 - ready to merged
Please test #2798 on image number >= tizen-unified_20210413.2.
