### ISSUE TITLE
NUI Lottie performance

### ISSUE THREAD

**Issue by Kamil-Stepaniuk** [Samsung/TizenFX#2781]
As can be observed in sample https://github.sec.samsung.net/NUI/TizenNUISamples/tree/master/LottieViewSample LottieAnimationView does not work properly. Animation is rendered slower and therefore its duration is longer than it should be.

**Comment by taehyub** [comment]
This seems to be a frame drop problem for redering complicated vector object of lottie animation.
To resolve this problem make NUI animation logic skip the frames if frame drop occurs.
