### ISSUE TITLE
Issues with Tizen.Applications.DirectoryInfo constructor 

### ISSUE THREAD

**Issue by hellhound858** [Samsung/TizenFX#2820]
Hello,

Having some issues creating an object of this class Tizen.Applications.DirectoryInfo

Need to get file path to create text file on wearable device to store data for my application. 

Here is the error:
DirectoryInfo does not contain a constructor that takes 0 arguments.

The line causing the error:
`private Tizen.Applications.DirectoryInfo DI = new Tizen.Applications.DirectoryInfo();`

The file:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Tizen.Applications;
namespace TimeTable
{
    class Storage
    {
        private Tizen.Applications.DirectoryInfo DI = new Tizen.Applications.DirectoryInfo();
        
        public void createFile(String lessonToWrite, String dateOfLesson)
        {
            string path = Data;
            if (!File.Exists(path))
            {
                // Create a file to write to.
                using (StreamWriter sw = File.CreateText(path)){
                    sw.WriteLine(lessonToWrite);
                    sw.WriteLine(dateOfLesson);
                }
            }
        }

        public List<String> readFile()
        {
            string path = Data;

            List<String> dataRead = new List<string>();

            using (StreamReader sr = File.OpenText(path))
            {
                string s;
                while ((s = sr.ReadLine()) != null)
                {
                    dataRead.Add(s);
                }
                return dataRead;
            }

        }
    }
}   

```

**Comment by myroot** [comment]
Because, you must to get from `Application` class object
https://github.com/Samsung/TizenFX/blob/6bd86c1a157e4ba75da5c515cf880c735fa6ebb2/src/Tizen.Applications.Common/Tizen.Applications/Application.cs#L46

``` c#
 var dirInfo = Application.Current.DirectoryInfo;
```

**Comment by hellhound858** [comment]
Now get a permissions error, sorry to be a bother.

Error:
"Access to the path '/opt/media/sdcard/apps/owner/apps_rw/org.tizen.example.TimeTable/shared/data/' is denied."

Thank you for all help provided.

**Comment by myroot** [comment]
You need to declare privilege http://tizen.org/privilege/appdir.shareddata

https://samsung.github.io/TizenFX/master/api/Tizen.Applications.ApplicationInfo.html#Tizen_Applications_ApplicationInfo_SharedDataPath

**Comment by hellhound858** [comment]
Ok so found the privileges that I need but they are not located in the tizen-manifest.xml privileges page.

These are the privileges:

http://tizen.org/privilege/filesystem.read
http://tizen.org/privilege/filesystem.write

I tried searching for them the don't exist also tried adding them as custom privileges also does not work.

Again thank you for your help.

**Comment by hellhound858** [comment]
Yeah tried defining privileges. Unfortunately they don't exist in the tizen-manifest.xml thing, tried searching for them.

Changed code to this (my create file function):
  
```
 public void createFile(String lessonToWrite, String dateOfLesson)
        {
            var dirInfo = Application.Current.DirectoryInfo;
            
            string path = dirInfo.Data;
            if (!File.Exists(path))
            {
                // Create a file to write to.
                using (StreamWriter sw = File.CreateText(path)){
                    sw.WriteLine(lessonToWrite);
                    sw.WriteLine(dateOfLesson);
                }
            }
        }
```

Found the permissions that will mostly likely be used for this updated code from that link you sent me. These are the permissions:
http://tizen.org/privilege/filesystem.read
http://tizen.org/privilege/filesystem.write

Cant find either in:
tizen-manifest.xml 

Any ideas?

**Comment by hellhound858** [comment]
Just realised the two privileges I linked are for web not .net.

Do you know of a .net alternative because I cant find one. :(

**Comment by hellhound858** [comment]
Changed the code back to:

**Comment by hellhound858** [comment]
Changed the code back to:
`string path = dirInfo.SharedData;`

Tried using the perm that you sent me:
http://tizen.org/privilege/appdir.shareddata

Could not find it in:
tizen-manifest.xml -> privileges 
When I tried to search for it so I tried adding it as a custom privilege.

I still get the error:
"Access to the path '/opt/media/sdcard/apps/owner/apps_rw/org.tizen.example.TimeTable/shared/data/' is denied."

**Comment by myroot** [comment]
You can edit directly tizen-manifest.xml file with text editor
``` xml
    <privileges>
        <privilege>http://tizen.org/privilege/appdir.shareddata</privilege>
    </privileges>
```

**Comment by myroot** [comment]
if you use external storage you need to add this privilege http://tizen.org/privilege/externalstorage.appdata

**Comment by hellhound858** [comment]
Yeah still get the same error.

My code

```
<?xml version="1.0" encoding="utf-8"?>
<manifest package="org.tizen.example.TimeTable" version="1.0.0" api-version="5.5" xmlns="http://tizen.org/ns/packages">
    <profile name="wearable" />
    <ui-application appid="org.tizen.example.TimeTable" exec="TimeTable.dll" multiple="false" nodisplay="false" taskmanage="true" api-version="6" type="dotnet" launch_mode="single">
        <label>TimeTable</label>
        <icon>TimeTable.png</icon>
        <metadata key="http://tizen.org/metadata/prefer_dotnet_aot" value="true" />
        <splash-screens />
    </ui-application>
    <shortcut-list />
    <privileges>
        <privilege>http://tizen.org/privilege/appdir.shareddata</privilege>
		<privilege>http://tizen.org/privilege/externalstorage.appdata</privilege>
    </privileges>
    <dependencies />
    <provides-appdefined-privileges />
</manifest>
```

**Comment by hellhound858** [comment]
Unsure what to do

**Comment by myroot** [comment]
Which device you use?
please post a new issue including your current issue
