### ISSUE TITLE
[Tizen.​Multimedia.​Vision] BarcodeGenerator

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/TizenFX#296]
https://developer.tizen.org/dev-guide/csapi/api/Tizen.Multimedia.Vision.BarcodeGenerator.html

No feature link in API documentation.

Also method GenerateImage(message, qrConfig, imageConfig, config) have an error in exception throwing:

throws Invalid Data Exception when trying to save image to a path with no permissions. In other cases it was throwing Invalid Path Exception. It was misleading when I was trying to solve why I can't generate image.

**Comment by WonyoungChoi** [comment]
close old issue, please re-open if necessary.
