### ISSUE TITLE
[Tizen.​Applications] AppControl - Pick/Audio

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/TizenFX#297]
In app there is a new app control defined with AppControlOperations set to Pick. Mime is set to "audio/*". Later there is SendLaunchRequest executed with proper callback event handler.

At this point we are in music explorer and there is 3 filters at the top (Tracks, Artists, Albums). Switching between these 3 doesn't cause any problems. Also picking up single track from Tracks works. Problem is when user selects album or artist (without picking any particular track) and then user wants to change to another category (any of them).  Application crashes and goes back to application that launched request. Couple of times it did crash also the application that launched it.

Code snippet:

```cs
var pickAppcontrol = new AppControl
            {
                Operation = AppControlOperations.Pick
            };

pickAppcontrol.Mime = "audio/*";

AppControl.SendLaunchRequest(pickAppcontrol, MyFileSelectedCallback);
```

See also TNEXT-15229

**Comment by jsobczuk** [comment]
Hi
Is the issue fixed already?

**Comment by semun-lee** [comment]
Sorry for late. I'm not sure if this issue is fixed or not. I'll assign this issue to the app developer.
