### ISSUE TITLE
[Xamarin.Forms.Platform.Tizen] Stepper - feature request

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/TizenFX#303]
We needed Stepper in application that is vertical not horizontal. There was a renderer class made 
because Stepper class does not have any attributes responsible for it.

At first it was working good, but later one of testers created an issue that this stepper should 
also be editable (user can change input from mobile keyboard), so this was also changed in 
VerticalStepper class. Almost everything was good except one thing :)

When the value is clicked it works properly, value highlights and keyboard pops up.
![image](https://user-images.githubusercontent.com/39958609/41652917-d89769a2-7484-11e8-8c7e-046900b96b9b.png)

But when the value is clicked and the click is hold, value's color is set to white so on white background it dissapear.
![image](https://user-images.githubusercontent.com/39958609/41652946-ea8fdebe-7484-11e8-83fa-b897ad74f37c.png)

Even though we found a way to omit the problem I'm writing about this to be considered to join 
these features to Stepper class:

-vertical stepper
-editable stepper (that does not cause problem described above)

Both seems to be very common and used :)

See also - TNEXT-15244

**Comment by rookiejava** [comment]
This issue seems out of scope of TizenFX. Please submit an issue [right place](https://github.sec.samsung.net/dotnet/Xamarin.Forms).
