### ISSUE TITLE
[Media​Controller] Lack of support for the custom commands

### ISSUE THREAD

**Issue by mszperna** [Samsung/TizenFX#348]
Current Tizen.Multimedia.Remoting API does not support Media Controller method to send custom command to a server. This option is availiable in Native API and for unknown reason has not been implemented in .NET version. This significantly limits the possibilities of using the Media Control API in applications. Is there any reason why the custom commands are not implemented? Is there any replacement for them?

**Comment by hsgwon** [comment]
It's added in C# level 5. 
Please refer RequestAsync() method and CustomCommand class.
