### ISSUE TITLE
Improper BaselineDpi is given for UHD screen.

### ISSUE THREAD

**Issue by p-czaja** [Samsung/TizenFX#3603]
For emulator with UHD resolution (3840x2160 px) property [BaselibeDpi](https://github.com/Samsung/TizenFX/blob/888cdf6ecfe738a21174e0c406d312aacfbbf77b/src/Tizen.NUI/src/public/Utility/GraphicsTypeManager.cs#L128) retutns improper value.
Emulator image: [tizen-unified_20210916.1](http://download.tizen.org/snapshots/tizen/unified/tizen-unified_20210916.1/)

- DPI visible in emulator's details: **DPI: 881**

![UHD_emu_dpi](https://user-images.githubusercontent.com/35915826/134342041-fe4a643f-6734-41e3-9040-c4c474cfe303.png)

- DPI visible in [GraphicsTypeTest](https://github.com/Samsung/TizenFX/blob/888cdf6ecfe738a21174e0c406d312aacfbbf77b/test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GraphicsTypeTest.cs#L34): **DPI: 314**

![UHD_emu_dpi_sample](https://user-images.githubusercontent.com/35915826/134344015-189aeff3-18c9-41fd-b1ae-77c4aeb5c31f.png)

**Comment by everLEEst** [comment]
we get dpi from ecore and ecore calculate dpi from wayland information, so if they give wrong infomation value can be wrong.
one other way to get dpi is using System.Info, so I'll check they give proper dpi values.
thank you for the report.
