### ISSUE TITLE
[Applications] ProxyBase, Hard to extend (IDisposable)

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#397]
`void Dispose(bool)`
It should be protected virtual to allow extend. 

https://github.com/Samsung/TizenFX/blob/bb6968aeb4e7b3ae9fb0cbbc283f5b52550b15e9/src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs#L170

But, ProxyBase/StubBase does not

Please refer this article
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern

**Comment by pjh9216** [comment]
Now that the previous ACR is ongoing, I'll add the new ACR later.

**Comment by myroot** [comment]
https://github.com/Samsung/TizenFX/pull/606
