### ISSUE TITLE
`new CultureInfo()` throws an exception in Invariant Mode. (on .NET 6)

### ISSUE THREAD

**Issue by HJLeee** [Samsung/TizenFX#3994]
The below exception is thrown inside `OnCreate()` when invariant mode is enabled.

```
E/STDERR  ( 3552): Unhandled exception. System.TypeInitializationException: The type initializer for 'Tizen.Applications.CultureInfoHelper' threw an exception.
E/STDERR  ( 3552):  ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
E/STDERR  ( 3552): en-US is an invalid culture identifier.
E/STDERR  ( 3552):    at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride) in System.Private.CoreLib.dll:token 0x600257c+0x2f
E/STDERR  ( 3552):    at Tizen.Applications.CultureInfoHelper..cctor() in Tizen.Applications.Common.dll:token 0x60000d8+0x1a
E/STDERR  ( 3552):    --- End of inner exception stack trace ---
E/STDERR  ( 3552):    at Tizen.Applications.CultureInfoHelper.GetCultureName(String locale) in Tizen.Applications.Common.dll:token 0x60000d7+0x0
E/STDERR  ( 3552):    at Tizen.Applications.CoreApplication.ConvertCultureInfo(String locale) in Tizen.Applications.Common.dll:token 0x60000bb+0x6
E/STDERR  ( 3552):    at Tizen.Applications.CoreApplication.ChangeCurrentUICultureInfo(String locale) in Tizen.Applications.Common.dll:token 0x60000bd+0x0
E/STDERR  ( 3552):    at Tizen.Applications.CoreApplication.OnCreate() in Tizen.Applications.Common.dll:token 0x60000b1+0x6
E/STDERR  ( 3552):    at Tizen.NUI.NUIApplication.OnCreate() in Tizen.NUI.dll:token 0x6000d09+0x0
E/STDERR  ( 3552):    at NUITemplate.Program.OnCreate() in NUITemplate.dll:token 0x6000001+0x1
E/STDERR  ( 3552):    at Tizen.NUI.NUICoreBackend.OnInitialized(Object source, NUIApplicationInitEventArgs e) in Tizen.NUI.dll:token 0x60000ed+0x7b
E/STDERR  ( 3552):    at Tizen.NUI.Application.OnApplicationInit(IntPtr data) in Tizen.NUI.dll:token 0x6000072+0x3b
```

This occues on .NET 6 environment as of [this](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode) breaking change.
> If an app attempts to create a culture that's not the invariant culture, a [CultureNotFoundException](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.culturenotfoundexception) exception is thrown.

Please review the code in the below.
https://github.com/Samsung/TizenFX/blob/239a69bf5f92ac5cfe9c581b257b9f5a6cb286a9/src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs#L146-L147

**Comment by HJLeee** [comment]
To test this, you can put `--invariant` in the `dotnet.loader` or `dotnet.launcher` file , or run CSFS app on a .NET 6 enabled DTV target.

**Comment by hjhun** [comment]
When the globalization-invariant mode is enabled, creating a new CultureInfo() throws a CultureNotFoundException exception.
I've prepared a new PR to handle the exception for globalization-invariant mode.
https://github.com/Samsung/TizenFX/pull/3998
If it's not a good solution, please tell me some advice.
