### ISSUE TITLE
[Tizen.Applications] ApplicationInfo.SharedDataPath returns empty string

### ISSUE THREAD

**Issue by vincent-kwon** [Samsung/TizenFX#405]
ApplicationInfo.SharedDataPath and  DirectoryInfo.SharedData  return empty strings.

**Comment by myroot** [comment]
I was test in Tizen4.0 TV emulator
Log
```
E/CAPI_APPFW_APP_MANAGER(20313): app_manager.c: app_manager_error(72) > [app_manager_get_shared_data_path] Not
 supported(0xc0000002)
W/Tizen.Applications(20313): ApplicationInfo.cs: SharedDataPath(307) > Failed to get the SharedDataPath of org.tizen.example.TwitchClips.Tizen. err = -1073741822
```

**Comment by myroot** [comment]
it check existed of shared directory
``` C
337 API int aul_get_app_shared_data_path_by_appid(const char *appid, char **path)
338 {
339	int ret;
340	char *ret_path;
341
342	if (path == NULL)
343		return AUL_R_EINVAL;
344
345	ret = __get_path(&ret_path, appid, _SHARED_DATA_DIR, getuid());
346	if (ret != AUL_R_OK)
347		return ret;
348
349	ret = access(ret_path, F_OK);
350	if (ret == 0) {
351		*path = ret_path;
352	} else {
353		free(ret_path);
354		return AUL_R_EREJECTED;
355	}
356
357	return AUL_R_OK;
358}
```
but shared/data directory was not created
```
# pwd
/home/owner/apps_rw/org.tizen.example.Sample.Tizen/shared
# ls -al
total 16
drwxr-xr-x 3 owner  users  4096 Aug 24 16:27 .
drwxr-xr-x 5 owner  users  4096 Aug 24 16:27 ..
lrwxrwxrwx 1 app_fw app_fw   61 Aug 24 16:27 res -> /opt/usr/globalapps/org.tizen.example.Sample.Tizen/shared/
res
drwxr-xr-x 2 owner  users  4096 Aug 24 16:27 trusted
#
```

**Comment by semun-lee** [comment]
Hmm... "shared/data" directory is created only when an application declares the "http://tizen.org/privilege/appdir.shareddata". 

ApplicationInfo.SharedDataPath is designed as property and throwing exception is not recommended.. How do you think adding description of appdir.shareddata privilege and the meaning of empty string value?

**Comment by myroot** [comment]
This restriction was not mentioned in TizenFX document

Guide
https://developer.tizen.org/development/training/native-application/understanding-tizen-programming/file-system-directory-hierarchy

Reference
https://samsung.github.io/TizenFX/master/api/Tizen.Applications.ApplicationInfo.html#Tizen_Applications_ApplicationInfo_SharedDataPath

Need to update API reference

**Comment by semun-lee** [comment]
I'll update the guide and reference. Thanks.

**Comment by semun-lee** [comment]
Added description with #437
