### ISSUE TITLE
RelativeLayout Issue on DefaultLinearItem and DefaultGridItem.

### ISSUE THREAD

**Issue by everLEEst** [Samsung/TizenFX#4161]
https://github.com/Samsung/TizenFX/pull/4160

Currently it has few bug in the sample.
1. DefaultLinearItem Two Line is not show correctly.
2. DefaultLinearItem Icon and Extra Margin is not properly applied.
3. DefaultGridItem text is not property placed.
4. DefaultGridItem Image cannot be clipped cornerRadius when it's parent is ClipToChildren.

**Comment by everLEEst** [comment]
to reproduce 4. DefaultGridItem Image cannot be clipped cornerRadius when it's parent is ClipToChildren.
firstly you need to remove cornerRadius on ImageView on ImageViewStyle of DefaultGridItemStyle.

**Comment by everLEEst** [comment]
![1 2](https://user-images.githubusercontent.com/29924275/164168552-0a053822-deea-4266-939e-93d76bb4b0ae.PNG)
![3 4](https://user-images.githubusercontent.com/29924275/164168555-ac9d1f7f-8872-41dd-b8a5-0be47bd4d54a.PNG)

**Comment by everLEEst** [comment]
노란색 영역이 실제 텍스트가 나왔어야 했으나 나오지 않았거나 잘못 위치한 경우이며
빨간 체크는 마진이 적용되지 않은 이슈이고
빨간 동그라미는 코너라디우스가 적용되지 않은 것을 확인할 수 있습니다.

**Comment by everLEEst** [comment]
4번은 확인 결과 Box4Shadow 와 CornerRadius ClippingMode 간 간섭 이슈로 보이며 우선 image에도 CornerRadius를 적용하는 것으로 우회하겠습니다.

**Comment by jaehyun0cho** [comment]
1번은 https://github.com/Samsung/TizenFX/pull/4219 으로 해결되었습니다.
2번 및 3번은 https://github.com/Samsung/TizenFX/pull/4214 으로 해결되었습니다.
