### ISSUE TITLE
[VoiceControl] Support for Wearable profile?

### ISSUE THREAD

**Issue by mszperna** [Samsung/TizenFX#440]
Does the current VoiceControl API (.NET C#) support the wearable profile? All attempts to use this API while creating a wearable application have failed.

**Comment by mszperna** [comment]
@hsgwon could You please give me any information?

**Comment by hsgwon** [comment]
@syeonholic Please check this issue.

**Comment by mszperna** [comment]
@hsgwon @syeonholic Any update?

**Comment by WonyoungChoi** [comment]
close this old issue. If necessary, re-open without hesitation.
and VoiceControl is also supported in wearable profile from API4.
