### ISSUE TITLE
[NFC] Privileges level mismatch

### ISSUE THREAD

**Issue by r-czerski** [Samsung/TizenFX#462]
Hello,

I am Samsung Project Leader and developer.

I faced an issue with NFC activation in C# API:
`NfcManager.SetActivationAsync(true);`

I have received following error while installing app on Galaxy Watch:
_key[error] val[-14] error message: :Check tizen-manifest.xml| - Current api-version = 4, |  certificate signature level = partner||[MISMATCHED_PRIVILEGE_LEVEL]| - http://tizen.org/privilege/nfc.admin|   >> Use at least platform signatured certificate.||:<-7>_ 

The documentation points out that I need to use PARTNER certificate level, but above error message tells that I need to use PLATFORM cert level.
https://developer.tizen.org/development/guides/.net-application/connectivity-and-wireless/nfc#manager_activating_nfc_device

Can you please tell me what is the correct level and if the documentation is ok or invalid?

What is more Native and Web APIs
have PUBLIC level for the http://tizen.org/privilege/nfc.admin
https://developer.tizen.org/development/training/native-application/understanding-tizen-programming/security-and-api-privileges#wearable_native

Thanks in advance for help.

rc

**Comment by myroot** [comment]
>http://tizen.org/privilege/nfc.admin
>Allows the application to change NFC settings, such as switching NFC on and off.
This is a platform privilege for a native application and a public privilege for a Web application

http://tizen.org/privilege/nfc.admin is platform level privileges 
.net application has same policy with native application
