### ISSUE TITLE
[Tizen.Applications] The Badge API does not work correctly for a text message.

### ISSUE THREAD

**Issue by mszperna** [Samsung/TizenFX#512]
Hello,
I am a Samsung developer, I found the following bug: The Badge API has a problem when we use Control Panel to simulate a new message - **the BadgeControl.Changed event is not raised**. Therefore, it is not possible to implement correct handling of new message notifications in the application.

CORRECT BEHAVIOR:

Initial state:
![1_initial_state](https://user-images.githubusercontent.com/31132452/46875664-8e909600-ce3c-11e8-80ef-471c6ea6f843.png)

New call incoming:
![2_incoming_call](https://user-images.githubusercontent.com/31132452/46875672-98b29480-ce3c-11e8-8d6c-6a44857d48fe.png)

The number of notifications about missed calls has increased:
![3_notif_increased](https://user-images.githubusercontent.com/31132452/46875677-9e0fdf00-ce3c-11e8-93db-12c795225c6b.png)

WRONG BEHAVIOR:

New message notification arrives:
![4_incoming_message](https://user-images.githubusercontent.com/31132452/46875721-c4ce1580-ce3c-11e8-86de-baae50f152c1.png)

Text message badge has not changed:
![5_not_changed](https://user-images.githubusercontent.com/31132452/46875774-e6c79800-ce3c-11e8-8cf3-4547dbf22b2d.png)

Can you fix this issue?

**Comment by semun-lee** [comment]
@mszperna , could you share the code you used?

**Comment by mszperna** [comment]
It seems to me that this issue should be reopened, because the bug still exists. Attachement 
[BadgeIssue.zip](https://github.com/Samsung/TizenFX/files/2713090/BadgeIssue.zip) is an example of a very basic code demonstrating the problem. The BadgeControl.Changed event is invoked for example for missed calls but **when the emulator receives a new text message the event is not invoked**.

@semun-lee, @myroot

**Comment by myroot** [comment]
This seems to be a issue of the message service.
the badge of app(org.tizen.w-message) is not created when message was received

**Comment by mszperna** [comment]
Thank you for your answer @myroot . 
Could you please specify where the bug exists, that the badge of app(org.tizen.w-message) is not created when a new message is received? Is this a problem with the API?  Or maybe an emulator?

**Comment by myroot** [comment]
it seem to issue of message frameworks(daemon)
But, In product (galaxy watch) working well
