### ISSUE TITLE
[Multimedia.Player] PlayerDisplaySettings.SetRoi didn't accept negative position

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#514]
Tizen.Multimedia.PlayerDisplaySettings.SetRoi didn't accept negative position. 
But Application frequently use negative position when view was placed on scroller.

It seem to native layer issue
```
I/TIZEN_N_PLAYER( 2645): legacy_player.c: legacy_player_set_display_mode(1332) > [legacy_player_set_display_mode] mode:5
D/MM_PLAYER( 2645): mm_player_attrs.c: __mmplayer_apply_attribute(195) >  param_name: display_method
D/MM_PLAYER( 2645): mm_player_priv.c: _mmplayer_update_video_param(2611) > param_name : display_method
D/MM_PLAYER( 2645): mm_player_priv.c: _mmplayer_update_video_param(2615) > check display surface type attribute: 0
D/MM_PLAYER( 2645): mm_player_priv.c: __mmplayer_update_wayland_videosink_video_param(2573) > param_name : display_method
D/MM_PLAYER( 2645): mm_player_priv.c: __mmplayer_video_param_set_display_method(2463) > set video param : method 5
E/MM_COMMON( 2645): mm_attrs_private.c: mmf_attribute_validate_int(351) > [mmf_attribute:display_win_roi_x] out of range[min 0, max 2
147483647, set -188]
```

**Comment by eunhaechoi** [comment]
There is restriction of negative x, y position in platform side.
We will check and modify it to allow it.
Thank you.

**Comment by songgot** [comment]
There are two ways for rendering video in tizen platform, UI and overlay.
UI and Overlay can accept negative position. but libmm_player don't accept negative position when rendering by Overlay. This seems to be an error. I will check and fix it.

**Comment by songgot** [comment]
I resolved it as below
https://review.tizen.org/gerrit/#/c/platform/core/multimedia/libmm-player/+/195176/
