### ISSUE TITLE
[Tdbc] Avoid managed obj creation.

### ISSUE THREAD

**Issue by HJLeee** [Samsung/TizenFX#5207]
Tracking for TFM upversion task.
https://github.com/Samsung/TizenFX/pull/5145#discussion_r1173201322

I cannot assign @jeremy-jang for this.

cc/ @pjh9216

**Comment by HJLeee** [comment]
cc/ @JoonghyunCho @sung-su for net6.0 tfm

**Comment by JoonghyunCho** [comment]
The base TargetFramework for TizenFX is updated to `net6.0` from 11.0.0.17954 version.
