### ISSUE TITLE
Await at widget problem

### ISSUE THREAD

**Issue by kstepaniuk** [Samsung/TizenFX#628]
Performing UI operations at widget and mixing asynchronous tasks with them is unsafe. Awaiting on task that makes asynchronous calls doesn’t guarantee that execution resumes on the same thread (UI thread in this case). In contrast, full screen UI application works correctly.
Demonstrator shows this behavior logging thread Id before and after Delay. For widget it logs other id. Furthermore, I noticed widget has no implementation of synchronization context.

[WidgetAwait.zip](https://github.com/Samsung/TizenFX/files/2703099/WidgetAwait.zip)

    Nuget Packages:
    Tizen.NET 5.0.0.14562
    Tizen.NET.Sdk 1.0.1
    Affected Devices:
    FamilyHub
    Tizen4/Unified 4.0.0 (arm)
    VERSION = 4.0.0
    CODENAME = Next
    BUILD_ID=tizen-4.0-da-fhub4_20181219.1_FHUB4R-KM-US-RF9500-AD-RELEASE

**Comment by myroot** [comment]
Need to set SynchronizationContext at initial time

https://github.com/Samsung/TizenFX/blob/c905a7d604edc941f4c391a41f308f0e6213d150/src/Tizen.Applications.WidgetApplication/Tizen.Applications.CoreBackend/WidgetCoreBackend.cs#L110-L111

https://github.com/Samsung/TizenFX/blob/c905a7d604edc941f4c391a41f308f0e6213d150/src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/DefaultCoreBackend.cs#L125-L127
