### ISSUE TITLE
[MediaContent] API Usability - MediaDataReader

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#71]
IEnumerable<T> is provide more flexible interface and more familiar to C# developer. 
any reason to use MediaDataReader?

**Comment by coderhyme** [comment]
It is open to implement IEnumerable, but there are some issues with the native implementation.
will be considered after the issues are addressed.

**Comment by myroot** [comment]
MediaDataReader only can be created from IEnumerable
and there is no native APIs related with it.

Why not use IEnumerable directly?

**Comment by coderhyme** [comment]
Like I said, there are issues with the native implementation. 
Current implementation is temporary. It should be replaced.

**Comment by myroot** [comment]
How about use IEnumerator<T>?
It is a same interface with MediaDataReader except Reset, 
But, It it not necessarily

```
The Reset method is provided for COM interoperability. It does not necessarily need to be implemented; instead, the implementer can simply throw a NotSupportedException. However, if you choose to do this, you should make sure no callers are relying on the Reset functionality.
```

**Comment by myroot** [comment]
Reason to not use IEnumerable 
 - To dispatch item lazy on demand 

Reason to not use IEnumerator
 ?
