### ISSUE TITLE
SmartEvent leak

### ISSUE THREAD

**Issue by ppaneksamsung** [Samsung/TizenFX#719]
Hello,

We develop the application based on Xamarin.Forms. Our application is hosted on github: https://github.com/SamsungDForum/JuvoPlayer

During memory profiling, we noticed that a number of ElmSharp.SmartEvent and ElmSharp.SmartEvent<EventArgs> objects increases, every time we call a Xamarin.Forms.ImageSource.FromFile(string file) method.

![elm-sharp-smart-event-leak 1](https://user-images.githubusercontent.com/29063919/53006782-309d3c00-3436-11e9-8d20-80a3f8440092.png)

On Tizen platform, Xamarin.Forms.ImageSource is based on ElmSharp.Image class.

We found 2 problems:

1. Please take a look at: https://github.com/Samsung/TizenFX/blob/142bb4717dd7ed4fd4077a4cd9d67d1fc2a78140/src/ElmSharp/ElmSharp/Image.cs#L510-L548

Two SmartEvent objects are created in LoadAsync() method, however only one of them is disposed:
- loadReady event is disposed when loading completes successfully
- loadError event is disposed when loading fails

A simple fix for this issue is to dispose both events when one of them completes, for example:

```
public Task<bool> LoadAsync(string file, CancellationToken cancellationToken = default(CancellationToken))
{
    if (file == null)
        throw new ArgumentNullException("file");

    Interop.Elementary.elm_image_async_open_set(RealHandle, true);
    Interop.Elementary.elm_image_preload_disabled_set(RealHandle, false);

    var tcs = new TaskCompletionSource<bool>();
    var loadReady = new SmartEvent(this, RealHandle, "load,ready");
    var loadError = new SmartEvent(this, RealHandle, "load,error");

    cancellationToken.Register(() =>
    {
        loadReady.Dispose();
        loadError.Dispose();

        if (tcs != null && !tcs.Task.IsCompleted)
        {
            tcs.SetCanceled();
        }
    });

    loadReady.On += (s, e) =>
    {
        loadReady.Dispose();
        loadError.Dispose();

        LoadingCompleted?.Invoke(this, EventArgs.Empty);
        if (tcs != null && !tcs.Task.IsCompleted)
        {
            tcs.SetResult(true);
        }
    };

    loadError.On += (s, e) =>
    {
        loadError.Dispose();
        loadReady.Dispose();

        LoadingFailed?.Invoke(this, EventArgs.Empty);
        if (tcs != null && !tcs.Task.IsCompleted)
        {
            tcs.SetResult(false);
        }
    };
```
The method LoadAsync(Stream, CancellationToken) has the same problem.

2. Please take a look at:
https://github.com/Samsung/TizenFX/blob/142bb4717dd7ed4fd4077a4cd9d67d1fc2a78140/src/ElmSharp/ElmSharp/SmartEvent.cs#L71-L78

When SmartEvent is being created, it registers itself in "EventLifeTracker". However, it's not deregistered   in Dispose method. We are able to workaround this problem by adding RemoveFromEventLifeTracker method to ElmSharp.EvasObject class and then call it in SmartEvent.Dispose, but this solution also requires modifications in ElmSharp.EvasObject.DisposeEvent and ElmSharp.EvasObject.MakeInvalidateEvent to avoid reentrancy issues.

```
// In: ElmSharp.EvasObject
internal void RemoveFromEventLifeTracker(IInvalidatable item)
{
    _eventStore.Remove(item);
}

// In: ElmSharp.SmartEvent
protected virtual void Dispose(bool disposing)
{
    if (disposing)
    {
        _sender.RemoveFromEventLifeTracker(this);
    }
    if (_handle != IntPtr.Zero)
    {
        foreach (var cb in _nativeCallbacks)
        {
            Interop.Evas.evas_object_smart_callback_del(_handle, _eventName, cb.callback);
        }
    }
    _nativeCallbacks.Clear();
}
```

**Comment by myroot** [comment]
Thanks reporting issue, It should be fixed.

Originally, SmartEvent only internally is used. And we don't allow different lifetime between target object and SmartEvent object

But, now these constraints is broken. and it could be memory leak. 

I will update some patch
