### ISSUE TITLE
[Security.TEEC] Memory leak

### ISSUE THREAD

**Issue by myroot** [Samsung/TizenFX#76]
It use `Marshal.AllocHGlobal` on constructor
https://github.com/Samsung/TizenFX/blob/3566375f1189cdcd03f869fae78eabd77bbe3a3b/src/Tizen.Security.TEEC/Tizen.Security.TEEC/Libteec.cs#L708

But, anywhere not freed with `Marshal.FreeHGlobal`
https://github.com/Samsung/TizenFX/blob/3566375f1189cdcd03f869fae78eabd77bbe3a3b/src/Tizen.Security.TEEC/Tizen.Security.TEEC/Libteec.cs#L726-L743

**Comment by terry2000s** [comment]
It has been resolved in the below commit. Please check again.
- [TEEC] Guard session close in destructor, apply 'Dispose Pattern'
https://github.com/Samsung/TizenFX/pull/64#pullrequestreview-91719058
