### ISSUE TITLE
my callback function cann't  be excuted

### ISSUE THREAD

**Issue by victorywkq** [Samsung/TizenFX#763]
when I want to get data from GPS modules,my device has been set on,but the callback function always can't be excuted.So I can't get data from GPS modules.the code as below:  wait for answer,tks sincerely.
e.g. 
			    if(location_manager_set_service_state_changed_cb(location_manager, location_state_cb, NULL) == LOCATIONS_ERROR_NONE)
			    {
			    	my_debug_print("wkqtest Location service callback added.");
			    }
			    // Starting service
			    if(location_manager_start(location_manager) == LOCATIONS_ERROR_NONE)
			    {
			    	my_debug_print("wkqtest Location service started.");
			    }
			}

			// On shutdown of your service:
			if (location_manager_unset_service_state_changed_cb(location_manager) == LOCATIONS_ERROR_NONE)
			{
				my_debug_print("wkqtest Location service callback removed.");
			}
			// It is not necessary to call location_manager_stop() just before calling
			// location_manager_destroy because the service is stopped automatically
			// before destruction.
			if (location_manager_destroy(location_manager) == LOCATIONS_ERROR_NONE)
			{
				my_debug_print("wkqtest Location manager destroyed.");
			    location_manager = NULL;
			}
///////////////////////////////
void location_state_cb(location_service_state_e state, void *user_data)
{
    if (state == LOCATIONS_SERVICE_ENABLED)
    {
    	my_debug_print("wkqtest Location service enabled.");
        double altitude, latitude, longitude, climb, direction, speed;
        double horizontal, vertical;
        location_accuracy_level_e level;
        time_t timestamp;
        int err = location_manager_get_location(location_manager, &altitude, &latitude, &longitude,
                                           &climb, &direction, &speed, &level,
                                           &horizontal, &vertical, &timestamp);
        if (err == LOCATIONS_ERROR_NONE)
        {
        	my_debug_print("wkqtest Location: %f,%f,%f,%f,%f,%f,%f,%f", altitude, latitude, longitude, climb, direction, speed, level, horizontal, vertical);
        }
        else
        {
        	my_debug_print("wkqtest Location error!");
	    //handle error here
        }
    }
    if (state == LOCATIONS_SERVICE_DISABLED)
    {
    	my_debug_print("wkqtest Location is disabled!");
    }
}

**Comment by victorywkq** [comment]
@pjh9216 @wiertel @liuxd @idkiller tks sincerely.

**Comment by myroot** [comment]
Hi, It is for Tizen.NET API

Please use this place https://developer.tizen.org/forums
