### ISSUE TITLE
[ElmSharp.Wearable][MoreOption] Item focus moves only between first and last item when using bezel

### ISSUE THREAD

**Issue by p-czaja** [Samsung/TizenFX#777]
It is not possible to select the option in menu using the bezel. Even if the bezel is rotated slightly, focus moves only between last and first option.

Steps to reproduce:
- install and run [ElmSharp.Wearable.Test](https://github.com/Samsung/TizenFX/tree/master/test/ElmSharp.Wearable.Test - extract
[tpk.zip](https://github.com/Samsung/TizenFX/files/3038387/tpk.zip) and use tpk file
- go to: 'MoreOptionTest' -> click the cue button -> try to use bezel to move between options items.
- focus moves only between first and last item

Image version: 
Model=Tizen5/Unified;
Build=tizen-unified_20181024.1;

Note that this functionality (the same tpk file) works fine on image:
Model=Tizen4/Unified;
Build=tizen-4.0-unified_20190306.1;

**Comment by rookiejava** [comment]
This issue doesn't seem to be reproduced in the latest version (5.5/6.0). Please re-open if you have same problem. Thank you.
