### ISSUE TITLE
[ElmSharp.Wearable][MoreOption] Dot indicator is moving when option is set and menu is opened again

### ISSUE THREAD

**Issue by p-czaja** [Samsung/TizenFX#778]
Dot indicating the item focus is moving on it own (when you select one option, click back button and and later open menu again).
Steps to reproduce:

- install and run [ElmSharp.Wearable.Test](https://github.com/Samsung/TizenFX/tree/master/test/ElmSharp.Wearable.Test - extract
[tpk.zip](https://github.com/Samsung/TizenFX/files/3038798/tpk.zip) and use tpk file
- go to: 'MoreOptionTest' 
- click the cue button
- click one of the items (not first) 
- click back button
- once again click the cue button
Result:
the dot indicating the item focus is moving to first item. 

Image version:
Model=Tizen5/Unified;
Build=tizen-unified_20181024.1;

Note that when using the same tpk file on image:
Model=Tizen4/Unified;
Build=tizen-4.0-unified_20190306.1;
after second cue button click, the dot indicates first item immediately (it does not move to it in a visible way)

**Comment by rookiejava** [comment]
This issue doesn't seem to be reproduced in the latest version (5.5/6.0). Please re-open if you have same problem. Thank you.
