### ISSUE TITLE
[WatchManager] No API for watch manager

### ISSUE THREAD

**Issue by mszperna** [Samsung/TizenFX#797]
Hello,
Native API provides watch manager functionality. It allows to manage watch faces, display and control them. **TizenFX does not provide any analogues.** More information about watch manager can be found in the file [watch_control.h](http://10.113.136.60/tizen-main/xref/platform/core/appfw/widget-viewer/watch-control/include/watch_control.h).

TizenFX should provide a **WatchManager API** that allows a developer to work with watch faces without the need to reference native functions.

Please give this issue a **higher priority** because it blocks a very important project.

**Comment by myroot** [comment]
Watch manager API is not for 3rd party application. 
TizenFX is a API set for 3rd party application.
