### ISSUE TITLE
[RemoteView] Cannot create an object using EflSharp

### ISSUE THREAD

**Issue by mszperna** [Samsung/TizenFX#798]
Currently to create **RemoteView** object we have to use **ElmSharp.EvasObject:**
_RemoteViewFactory.Create(**ElmSharp.EvasObject**, String, ...)._
There is no version of _RemoteViewFactory.Create(...)_ method, that takes **EflSharp** object as a parameter. Hence, we are forced to use ElmSharp in EflSharp project.

We need a new version of _RemoteViewFactory.Create(...)_ method, one that takes **EflSharp** object as a parameter

**Comment by mszperna** [comment]
@hsgwon Could You provide any informaton?

**Comment by hsgwon** [comment]
As I know, RemoteViewFactory class doesn't support EflSharp yet.
Mr. Junghoon Park(@pjh9216) who charges in C# application framework could answer your question.
Please contact him.

**Comment by WonyoungChoi** [comment]
Unfortunately, The EflSharp project has been suspended.
