### ISSUE TITLE
Cannot control flight mode and do not disturb mode.

### ISSUE THREAD

**Issue by j-troc** [Samsung/TizenFX#858]
Currently there is no way to set flight mode nor do not disturb mode in TizenFX.
Also in case of do not disturb mode there seems to be no way to check whether it's enabled.

We need ability to set flight mode and do not disturb mode.

**Comment by myroot** [comment]
You can only get state of flight mode. 
IMO, it is very dangerous function to open for 3rd party application. If it opened, it can be abused by malware.
