### ISSUE TITLE
[Tizen.Sensor] Gravity sensor

### ISSUE THREAD

**Issue by Kamil-Stepaniuk** [Samsung/TizenFX#884]
There is some correlation with values x and y in gravity sensor. Keeping one of this values on stable level and simultaneously changing the other value causes jumps on first value in a moment of crossing zero.

It can be visible on smart watch in attached application.
[org.tizen.example.Level-1.0.0.tpk.zip](https://github.com/Samsung/TizenFX/files/3276837/org.tizen.example.Level-1.0.0.tpk.zip)
tizen-release:
Tizen4/Unified 4.0.0 (arm)
VERSION = 4.0.0
CODENAME = Next
BUILD_ID=PLATFORM_PrdR500XX_20190315.002

Here is sample output. Value Y varies from 2 to 8 when X is close to 0.
[logs.txt](https://github.com/Samsung/TizenFX/files/3276851/logs.txt)

**Comment by WonyoungChoi** [comment]
close this old pr, please re-open if you necessary.
@bwikbs please regression check this problem in tizen 5.5 platform if you possible.
