### ISSUE TITLE
Problems with Tizen.Pims.Calendar

### ISSUE THREAD

**Issue by Staccator** [Samsung/TizenFX#939]
https://developer.tizen.org/development/guides/.net-application/personal-data/calendar 
Above guide is full of mistakes and code that is unusable, for example:
1. "var manager = new CalendarManager(); var record = manager.Get(CalendarViews.Event.Uri, eventId);"  There is not such function as Get in Calendar Manager
2. "var record;
while (record = list.GetCurrentRecord())
{
    string summary = record.Get<string>(CalendarViews.Event.Summary);
    list.MoveNext();
}"
This for sure haven't beet tested, how on earth is that first line there. Also GetCurrentRecord doesn't return bool
3.
"record.Set<int>(CalendarViews.Event.Bymonthday, "3,4,5");"
you specify int to be set, then use string instead

How am I supposed to use all the enums specified (like CalendarTypes.Recurrence) when it's impossible to use them ("record.set<CalendarTypes.Recurrence>();" won't work) 
Please update the guide or/and fix api, because there is no information available on how to properly use it.

**Comment by WonyoungChoi** [comment]
The guide was fixed. 
```csharp
var manager = new CalendarManager();
var record = manager.Database.Get(CalendarViews.Event.Uri, eventId);
```
